### ISSUE TITLE
How can I train my own model?

### ISSUE THREAD

**Issue by semeniak1997** [pasquini-dario/PLR#2]

**Comment by pasquini-dario** [comment]
Hi, 

sorry for the late reply. I've just updated the readme file with some instructions.

**Comment by Cherry1210** [comment]
请问 是不是没有一个攻击密码的文件
![7Z( 8~~51T8R8% $DU~( (P](https://user-images.githubusercontent.com/54921659/132218766-ac5de318-9784-4347-be22-65e2d63a1a51.png)
