### ISSUE TITLE
How to open the result

### ISSUE THREAD

**Issue by eiennnohorobi** [pasquini-dario/PLR#5]
Hi. Following the README, I executed the 
**python train.py CONF/arch1.gin** 
and  got five files under /PLR-master/PasswordGAN/HOME/CHECKPOINTS, I knew it is the result, but I dont know how to open it. Could you please help me and tell me how to open these files?

Thanks a lot.

**Comment by pasquini-dario** [comment]
Hi,

I'm moving in #4.
